on:
  push:
  pull_request:

jobs:
  build:
    name: BetterDiscord-build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Navigate to BetterDiscord folder
        run: cd ./client-mods/BetterDiscord

      - name: Install NPM packages
        run: npm install
      
      - name: Build BetterDiscord
        run: npm run build